### ISSUE TITLE
asyncio.async "invalid syntax"

### ISSUE THREAD

**Issue by wx672** [yyk123/XwareDesktop#4]
您好！我在参照[Ubuntu上编译安装说明](https://github.com/Xinkai/XwareDesktop/wiki/Ubuntu%E4%B8%8A%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E)进行编译，前几步（下载源码，安装依赖包……）都很顺利。做到dpkg-buildpackage时，编译过程遭遇如下报错：

```
*** Error compiling '/home/wx672/git/XwareDesktop/debian/xware-desktop/opt/xware-desktop/shared/thirdparty/aiohttp/server.py'...
  File "/home/wx672/git/XwareDesktop/debian/xware-desktop/opt/xware-desktop/shared/thirdparty/aiohttp/server.py", line 109
    self._request_handler = asyncio.async(self.start(), loop=self._loop)
                                        ^
SyntaxError: invalid syntax

*** Error compiling '/home/wx672/git/XwareDesktop/debian/xware-desktop/opt/xware-desktop/shared/thirdparty/aiohttp/worker.py'...
  File "/home/wx672/git/XwareDesktop/debian/xware-desktop/opt/xware-desktop/shared/thirdparty/aiohttp/worker.py", line 29
    self._runner = asyncio.async(self._run(), loop=self.loop)
                               ^
SyntaxError: invalid syntax

make[1]: *** [Makefile:161: install] Error 1
```
我不太了解python，google了一下，也没找到答案。不知该如何解决？我的系统环境是Debian testing.
```
Linux 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux
Python 3.7.2+ (default, Feb  2 2019, 14:31:48) 
[GCC 8.2.0] on linux
```

**Comment by wx672** [comment]
问题解决了。根据[Python 3.7 compatibility: asyncio.async and async keyword #24](https://github.com/garywiz/chaperone/issues/24) 里面的说法，只要把async改个名字就行了。编译虽然通过了（除了一个不重要的"failed to sign .dsc file"错误），但运行时还是报错，如下：
```
发行版: Debian GNU/Linux buster/sid 
桌面环境: 未知/未知
应用程序版本: e6c4642d3322a68e2f79328d9946790701490944

补充描述计算机。
可留空。

简述在什么情况下发生了这个问题。
可留空。

======================== 报告 ========================
错误发生在adapter-legacy

Traceback (most recent call last):
  File "/opt/xware-desktop/frontend/CrashReport/CrashAwareThreading.py", line 22, in new_run
    self._unpatched_run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/xware-desktop/frontend/libxware/adapter.py", line 158, in _startEventLoop
    asyncio.myasync(self.main())
AttributeError: module 'asyncio' has no attribute 'myasync'

======================== 结束 ========================
```
这显然是由于我把async改成了myasnc造成的，但不改又编译不通过，奈何？

**Comment by wx672** [comment]
把myasync改成ensure_future，重新编译、安装之后，可以运行了，虽然不知道为什么……

**Comment by TuvokYang** [comment]
Python 3.7 弃用了asyncio.async() 可以使用asyncio.ensure_future()替代
